version: "3"
services:
  mysql-standalone:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=hayfa
      
    ports:
      - 3306:3306
    restart : on-failure
    
  devopsproject:
    image: hayfaouni/examthouraya
    ports:
      - 8089:8089
    restart: unless-stopped
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/hayfa?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      -SPRING_DATASOURCE_USERNAME : root
      -SPRING_DATASOURCE_PASSWORD : 
    depends_on:
      - mysql-standalone
    links:
      - mysql-standalone:mysql-standalone